spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root123
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql:///enterprisejavabatch
    username: root
